language: node_js
node_js:
- '0.10'
- '0.12'
sudo: false
env:
  global:
  - secure: 0IoS5aWIlFm2InuHTMsqssnWH0zp/SXTHzQPjDvxqGWIuulPdZBd0WM17R7nxo/Msp6FG7QMMSWBAnePuPBTrs77iLEHHok/uqApsh/rLy1PQu4WZE5mlBBruZJftN/WO+2IV7WsmK0XeVrAxG7C875z/6zK/AGsJYLpyHP2jnM=
  - secure: HSxpg9/84xgfCwzojeu2Z7AGhIWTLudMVbNIRelVBTDSO+ksLFKCb0nyeGCj6q+LcXKu7sX4ZgdQomllrNNxhl02xsO5Ux+Z4HRWFcIZolpTcFXhjW2dNOgi+JnaiK7Y5PmnNpCKbPqvjWMct4GFazWFmS1X9Jcg/h1GBgdtzk0=
